# Generated by Django 3.2.12 on 2024-02-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0002_auto_20240209_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='miles',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
