# Generated by Django 3.2.12 on 2024-02-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0003_auto_20240210_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
