# Generated by Django 3.2.12 on 2024-02-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0004_carmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='auction',
            field=models.CharField(max_length=256),
        ),
    ]
